name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [34, 35, 36]
      fail-fast: false 

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Cache Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    # Cache Android SDK per API level
    - name: Cache Android SDK
      id: cache-android
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/android/sdk
        key: ${{ runner.os }}-android-sdk-${{ matrix.api-level }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-

    - name: Install Android Command Line Tools
      if: steps.cache-android.outputs.cache-hit != 'true'
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
        cd /usr/local/lib/android/sdk/cmdline-tools
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        sudo unzip -q cmdline-tools.zip -d latest
        sudo rm cmdline-tools.zip

    - name: Set Android Env Vars
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install SDK packages
      if: steps.cache-android.outputs.cache-hit != 'true'
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-${{ matrix.api-level }}" "build-tools;${{ matrix.api-level }}.0.0"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build project
      run: ./gradlew build --stacktrace

    - name: Run Unit Tests
      run: ./gradlew test --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-android-${{ matrix.api-level }}
        path: app/build/outputs/apk/debug/app-debug.apk
