name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK 35
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
        cd /usr/local/lib/android/sdk/cmdline-tools
        curl -s https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        sudo unzip -q cmdline-tools.zip -d .
        sudo mv cmdline-tools latest
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build project
      run: ./gradlew build --stacktrace

    - name: Run Unit Tests
      run: ./gradlew test --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk

